function Jpz = get_arakawa(psi,zeta,nx,ny,dx,dy)

Jpz = zeros(nx,ny);
coeff = 1/(3*dx*dy);

for ic = 1:nx
    i = ic + 1;
    for jc = 1:ny
        j = jc + 1;
        Jpz(ic,jc)= coeff*( ...
            (psi(i,j-1)+psi(i+1,j-1)-psi(i,j+1)-psi(i+1,j+1))*zeta(i+1,j) ...
            - (psi(i-1,j-1)+psi(i,j-1)-psi(i-1,j+1)-psi(i,j+1))*zeta(i-1,j) ...
            + (psi(i+1,j)+psi(i+1,j+1)-psi(i-1,j)-psi(i-1,j+1))*zeta(i,j+1) ...
            - (psi(i+1,j-1)+psi(i+1,j)-psi(i-1,j-1)-psi(i-1,j))*zeta(i,j-1) ...
            + (psi(i+1,j)-psi(i,j+1))*zeta(i+1,j+1) ...
            - (psi(i,j-1)-psi(i-1,j))*zeta(i-1,j-1) ...
            + (psi(i,j+1)-psi(i-1,j))*zeta(i-1,j+1) ...
            - (psi(i+1,j)-psi(i,j-1))*zeta(i+1,j-1));
        
    end
end